const authRoutes = require("./authRoute");
const buildingRoutes = require("./Landlord/buildingRoutes");
const floorRoutes = require("./Landlord/floorsRoutes");
const roomLandlordRoutes = require("./Landlord/roomsRoutes");
const packageRoutes = require("././Admin/packageRoutes");
const subscriptionRoutes = require("./subscriptionRoutes");
const furnitureRoutes = require("./Landlord/furnitureRoutes");
const userRoutes = require("./userRoute");
const regulationRoutes = require("./Landlord/regulationRoutes");
const buildingServiceRoutes = require("./Landlord/buildingServiceRoutes");
const postLandlord = require("././Landlord/postRoute");
const postUser = require("././User/postRoute");
const accountAdmin = require("././Admin/accountRoute");
const scheduleRoute = require("././Landlord/scheduleRoute");
const bookingRoute = require("././User/bookingRoute");
const bookingLandlord = require("././Landlord/bookingRoute");
const contactLandlord = require("././Landlord/contactRoute");
const termRoute = require("././Landlord/termRoute");
const contactRoute = require("././User/contactRoute");
const contractTemplateRoutes = require("././Landlord/contractTemplateRoutes");
const maintenanceRoutesLandlord = require("././Landlord/maintenanceRoutes");
const maintenanceRoutesUser = require("././User/maintenanceRoutes");
const staffRoute = require("./Landlord/staffRoute");
const revenueExpenditureRoute = require("./Landlord/revenueExpenditure");
const contractLandlord = require("././Landlord/contractRoute");
const notificationRoute = require("././Landlord/notificationRoute");
const contractRoute = require("././User/contractRoute");
const roomRoute = require("././User/roomRoute");
const roommateRoute = require("././User/roommateRoute");
const buildingRatingRoute = require("././User/buildingRatingRoute");

const routes = (app) => {
  app.use("/auth", authRoutes);
  app.use("/subscriptions", subscriptionRoutes);
  app.use("/admin/packages", packageRoutes);
  app.use("/admin/accounts", accountAdmin);

  app.use("/landlords/rooms", roomLandlordRoutes);
  app.use("/landlords/terms", termRoute);
  app.use("/landlords/floors", floorRoutes);
  app.use("/landlords/regulations", regulationRoutes);
  app.use("/landlords/furnitures", furnitureRoutes);
  app.use("/landlords/buildings", buildingServiceRoutes);
  app.use("/landlords/buildings", buildingRoutes);
  app.use("/landlords/posts", postLandlord);
  app.use("/landlords/schedules", scheduleRoute);
  app.use("/landlords/bookings", bookingLandlord);
  app.use("/landlords/contacts", contactLandlord);
  app.use("/landlords/contracts", contractLandlord);
  app.use("/landlords/contract-templates", contractTemplateRoutes);
  app.use("/landlords/maintenance", maintenanceRoutesLandlord);
  app.use("/landlords/staffs", staffRoute);
  app.use("/landlords/revenue-expenditure", revenueExpenditureRoute);
  app.use("/landlords/notifications", notificationRoute);
  app.use("/posts", postUser);
  app.use("/ratings", buildingRatingRoute);
  app.use("/roommates", roommateRoute);
  app.use("/bookings", bookingRoute);
  app.use("/contacts", contactRoute);
  app.use("/contracts", contractRoute);
  app.use("/profiles", userRoutes);
  app.use("/maintenance", maintenanceRoutesUser);
  app.use("/rooms", roomRoute);
};

module.exports = routes;
