const authRoutes = require("./authRoute");
const buildingRoutes = require("./Landlord/buildingRoutes");
const floorRoutes = require("./Landlord/floorsRoutes");
const roomRoutes = require("./Landlord/roomsRoutes");
const packageRoutes = require("././Admin/packageRoutes");
const subscriptionRoutes = require("./subscriptionRoutes");
const furnitureRoutes = require("./Landlord/furnitureRoutes");
const userRoutes = require("./userRoute");
const regulationRoutes = require("./Landlord/regulationRoutes");
const buildingServiceRoutes = require("./Landlord/buildingServiceRoutes");
const postLandlord = require("././Landlord/postRoute");
const postUser = require("././User/postRoute");
const accountAdmin = require("././Admin/accountRoute");
const scheduleRoute = require("././Landlord/scheduleRoute");
const bookingRoute = require("././User/bookingRoute");
const bookingLandlord = require("././Landlord/bookingRoute");
const contactLandlord = require("././Landlord/contactRoute");
const termRoute = require("././Landlord/termRoute");
const contactRoute = require("././User/contactRoute");
const contractTemplateRoutes = require("./Landlord/contractTemplateRoutes");

const routes = (app) => {
  app.use("/auth", authRoutes);
  app.use("/subscriptions", subscriptionRoutes);
  app.use("/admin/packages", packageRoutes);
  app.use("/admin/accounts", accountAdmin);
  app.use("/landlords/rooms", roomRoutes);
  app.use("/landlords/terms", termRoute);
  app.use("/landlords/floors", floorRoutes);
  app.use("/landlords/regulations", regulationRoutes);
  app.use("/landlords/furnitures", furnitureRoutes);
  app.use("/landlords/buildings", buildingServiceRoutes);
  app.use("/landlords/buildings", buildingRoutes);
  app.use("/landlords/posts", postLandlord);
  app.use("/landlords/schedules", scheduleRoute);
  app.use("/landlords/bookings", bookingLandlord);
  app.use("/landlords/contacts", contactLandlord);
  app.use("/landlords/contract-templates", contractTemplateRoutes);
  app.use("/posts", postUser);
  app.use("/bookings", bookingRoute);
  app.use("/contacts", contactRoute);
  app.use("/profiles", userRoutes);
};

module.exports = routes;
